(()=>{'use strict';
const C={livros:'dados/livros-biblia.json',pasta:'dados/biblias/demo',fav:'teologiaNinja_biblia_favoritos',notas:'teologiaNinja_biblia_anotacoes',cores:'teologiaNinja_biblia_marcacoes',fonte:'teologiaNinja_biblia_fonte'};
const E={livros:[],capitulo:null,versiculo:null,painel:null,modal:null,fonte:Number(localStorage.getItem(C.fonte)||1.15)};
const $=s=>document.querySelector(s);const ler=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}};const salvar=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const chave=(l,c,v)=>`${l}.${c}.${v}`;const ref=(l,c,v)=>`${E.livros.find(x=>x.id===l)?.abreviacao||l} ${c}:${v}`;
function preencherLivros(){const s=$('#livroBiblia');s.innerHTML='';['Antigo','Novo'].forEach(t=>{const g=document.createElement('optgroup');g.label=t==='Antigo'?'Antigo Testamento':'Novo Testamento';E.livros.filter(l=>l.testamento===t).forEach(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=l.nome;g.appendChild(o)});s.appendChild(g)})}
function preencherCapitulos(){const l=E.livros.find(x=>x.id===$('#livroBiblia').value),s=$('#capituloBiblia');s.innerHTML='';(l?.capitulosDisponiveis||[1]).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;s.appendChild(o)})}
async function carregar(){const l=$('#livroBiblia').value,c=$('#capituloBiblia').value;try{const r=await fetch(`${C.pasta}/${l}-${c}.json`);if(!r.ok)throw 0;E.capitulo=await r.json();$('#tituloCapitulo').textContent=`${E.capitulo.nome} ${E.capitulo.capitulo}`;renderizar();const u=new URL(location.href);u.searchParams.set('livro',l);u.searchParams.set('capitulo',c);history.replaceState(null,'',u)}catch{$('#listaVersiculos').innerHTML='<div class="alert alert-warning">Capítulo não incluído na base demonstrativa.</div>'}}
function renderizar(){const b=$('#buscaBiblia').value.trim().toLowerCase(),f=ler(C.fav),n=ler(C.notas),m=ler(C.cores);$('#listaVersiculos').innerHTML=E.capitulo.versiculos.filter(v=>!b||v.texto.toLowerCase().includes(b)).map(v=>{const k=chave(E.capitulo.livro,E.capitulo.capitulo,v.numero);let t=v.texto;if(b)t=t.replace(new RegExp(`(${b.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi'),'<mark>$1</mark>');return `<article class="versiculo-item ${m[k]?`marcacao-${m[k]}`:''} ${n[k]?'tem-anotacao':''} ${f[k]?'eh-favorito':''}" data-v="${v.numero}"><span class="versiculo-numero">${v.numero}</span><span class="versiculo-texto">${t}</span></article>`}).join('')}
function abrir(n){E.versiculo=E.capitulo.versiculos.find(v=>v.numero===Number(n));const k=chave(E.capitulo.livro,E.capitulo.capitulo,E.versiculo.numero);$('#tituloVersiculoPainel').textContent=ref(E.capitulo.livro,E.capitulo.capitulo,E.versiculo.numero);$('#textoVersiculoPainel').textContent=E.versiculo.texto;$('#btnFavoritarVersiculo').textContent=ler(C.fav)[k]?'♥ Remover dos favoritos':'♡ Favoritar';$('#btnAbrirInterlinear').href=`biblia.html?livro=${E.capitulo.livro}&capitulo=${E.capitulo.capitulo}&versiculo=${E.versiculo.numero}`;E.painel.show()}
function favorito(){const v=E.versiculo,k=chave(E.capitulo.livro,E.capitulo.capitulo,v.numero),f=ler(C.fav);if(f[k])delete f[k];else f[k]={livro:E.capitulo.livro,nome:E.capitulo.nome,capitulo:E.capitulo.capitulo,versiculo:v.numero,texto:v.texto};salvar(C.fav,f);renderizar();abrir(v.numero);listarFavoritos()}
function abrirNota(){const v=E.versiculo,k=chave(E.capitulo.livro,E.capitulo.capitulo,v.numero);$('#textoAnotacaoBiblia').value=ler(C.notas)[k]?.texto||'';E.modal.show()}
function salvarNota(){const v=E.versiculo,k=chave(E.capitulo.livro,E.capitulo.capitulo,v.numero),n=ler(C.notas),t=$('#textoAnotacaoBiblia').value.trim();if(t)n[k]={livro:E.capitulo.livro,nome:E.capitulo.nome,capitulo:E.capitulo.capitulo,versiculo:v.numero,textoBiblico:v.texto,texto:t};else delete n[k];salvar(C.notas,n);E.modal.hide();renderizar();listarNotas()}
function marcar(cor){const v=E.versiculo,k=chave(E.capitulo.livro,E.capitulo.capitulo,v.numero),m=ler(C.cores);if(cor)m[k]=cor;else delete m[k];salvar(C.cores,m);renderizar()}
function listarFavoritos(){const a=Object.values(ler(C.fav));$('#listaFavoritosBiblia').innerHTML=a.length?a.map(x=>`<article class="item-salvo"><strong>${ref(x.livro,x.capitulo,x.versiculo)}</strong><p class="mb-0 mt-2">${x.texto}</p></article>`).join(''):'<p class="text-secondary">Nenhum favorito.</p>'}
function listarNotas(){const a=Object.values(ler(C.notas));$('#listaAnotacoesBiblia').innerHTML=a.length?a.map(x=>`<article class="item-salvo"><strong>${ref(x.livro,x.capitulo,x.versiculo)}</strong><p class="small text-secondary mt-2">${x.textoBiblico}</p><p class="mb-0">${x.texto}</p></article>`).join(''):'<p class="text-secondary">Nenhuma anotação.</p>'}
function fonte(){E.fonte=Math.max(.9,Math.min(1.8,E.fonte));document.documentElement.style.setProperty('--biblia-font-size',`${E.fonte}rem`);localStorage.setItem(C.fonte,E.fonte)}
async function iniciar(){E.painel=new bootstrap.Offcanvas('#painelVersiculo');E.modal=new bootstrap.Modal('#modalAnotacaoBiblia');const r=await fetch(C.livros),d=await r.json();E.livros=d.livros;preencherLivros();const p=new URLSearchParams(location.search);$('#livroBiblia').value=p.get('livro')||'genesis';preencherCapitulos();if(p.get('capitulo'))$('#capituloBiblia').value=p.get('capitulo');$('#livroBiblia').onchange=()=>{preencherCapitulos();carregar()};$('#capituloBiblia').onchange=carregar;$('#buscaBiblia').oninput=renderizar;$('#btnLimparBuscaBiblia').onclick=()=>{$('#buscaBiblia').value='';renderizar()};$('#listaVersiculos').onclick=e=>{const x=e.target.closest('[data-v]');if(x)abrir(x.dataset.v)};$('#btnFavoritarVersiculo').onclick=favorito;$('#btnAnotarVersiculo').onclick=abrirNota;$('#btnSalvarAnotacaoBiblia').onclick=salvarNota;$('#btnCopiarVersiculo').onclick=async()=>{await navigator.clipboard.writeText(`${$('#tituloVersiculoPainel').textContent} — ${E.versiculo.texto}`)};document.querySelectorAll('[data-marcacao]').forEach(b=>b.onclick=()=>marcar(b.dataset.marcacao));$('#painelFavoritos').addEventListener('show.bs.offcanvas',listarFavoritos);$('#painelAnotacoes').addEventListener('show.bs.offcanvas',listarNotas);$('#btnAumentarFonte').onclick=()=>{E.fonte+=.1;fonte()};$('#btnDiminuirFonte').onclick=()=>{E.fonte-=.1;fonte()};$('#btnCapituloAnterior').onclick=()=>{$('#capituloBiblia').selectedIndex=Math.max(0,$('#capituloBiblia').selectedIndex-1);carregar()};$('#btnCapituloProximo').onclick=()=>{$('#capituloBiblia').selectedIndex=Math.min($('#capituloBiblia').options.length-1,$('#capituloBiblia').selectedIndex+1);carregar()};fonte();await carregar();if(p.get('versiculo'))abrir(p.get('versiculo'))}
document.addEventListener('DOMContentLoaded',iniciar)})();
