<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Glossário inglês -> português
|--------------------------------------------------------------------------
|
| A base MACULA fornece glosas em inglês. Este arquivo permite substituir
| automaticamente as glosas mais comuns. O que não estiver aqui será
| mantido em inglês para revisão posterior.
|
| Você pode ampliar este array aos poucos sem alterar o gerador.
|
*/

return [
    'God' => 'Deus',
    'Lord' => 'Senhor',
    'Jesus' => 'Jesus',
    'Christ' => 'Cristo',
    'Spirit' => 'Espírito',
    'Father' => 'Pai',
    'Son' => 'Filho',
    'grace' => 'graça',
    'peace' => 'paz',
    'love' => 'amor',
    'faith' => 'fé',
    'truth' => 'verdade',
    'word' => 'palavra',
    'life' => 'vida',
    'death' => 'morte',
    'sin' => 'pecado',
    'sins' => 'pecados',
    'salvation' => 'salvação',
    'righteousness' => 'justiça',
    'mercy' => 'misericórdia',
    'glory' => 'glória',
    'kingdom' => 'reino',
    'heaven' => 'céu',
    'earth' => 'terra',
    'world' => 'mundo',
    'church' => 'igreja',
    'brother' => 'irmão',
    'brothers' => 'irmãos',
    'beloved' => 'amado',
    'apostle' => 'apóstolo',
    'servant' => 'servo',
    'holy' => 'santo',
    'law' => 'lei',
    'commandment' => 'mandamento',
    'wisdom' => 'sabedoria',
    'knowledge' => 'conhecimento',
    'body' => 'corpo',
    'flesh' => 'carne',
    'heart' => 'coração',
    'light' => 'luz',
    'darkness' => 'trevas',
    'good' => 'bom',
    'evil' => 'mal',
    'works' => 'obras',
    'work' => 'obra',
    'hope' => 'esperança',
    'joy' => 'alegria',
    'prayer' => 'oração',
    'pray' => 'orar',
    'prophet' => 'profeta',
    'prophets' => 'profetas',
    'man' => 'homem',
    'men' => 'homens',
    'woman' => 'mulher',
    'children' => 'filhos',
    'people' => 'povo',
    'water' => 'água',
    'fire' => 'fogo',
    'bread' => 'pão',
    'blood' => 'sangue',
    'name' => 'nome',
    'day' => 'dia',
    'days' => 'dias',
    'time' => 'tempo',
    'eternal' => 'eterno',
    'new' => 'novo',
    'old' => 'antigo',
    'first' => 'primeiro',
    'last' => 'último',
    'one' => 'um',
    'two' => 'dois',
    'all' => 'todos',
    'every' => 'todo',
    'many' => 'muitos',
    'much' => 'muito',
    'not' => 'não',
    'and' => 'e',
    'but' => 'mas',
    'for' => 'pois',
    'because' => 'porque',
    'therefore' => 'portanto',
    'if' => 'se',
    'when' => 'quando',
    'who' => 'quem',
    'which' => 'que',
    'that' => 'que',
    'this' => 'isto',
    'these' => 'estes',
    'those' => 'aqueles',
    'in' => 'em',
    'on' => 'sobre',
    'with' => 'com',
    'without' => 'sem',
    'from' => 'de',
    'to' => 'para',
    'of' => 'de',
    'by' => 'por',
    'through' => 'por meio de',
    'before' => 'diante de',
    'after' => 'depois de',
    'now' => 'agora',
    'also' => 'também',
    'only' => 'somente',
    'again' => 'novamente',
    'we' => 'nós',
    'our' => 'nosso',
    'you' => 'vós',
    'your' => 'vosso',
    'they' => 'eles',
    'their' => 'deles',
    'he' => 'ele',
    'his' => 'seu',
    'I' => 'eu',
    'my' => 'meu',
];
