<?php

declare(strict_types=1);

return [
    'mateus' => [
        'sigla' => 'MAT',
        'ordem' => 40,
        'nome' => 'Mateus',
        'abreviacao' => 'Mt',
        'arquivo' => 'mateus.json',
    ],
    'marcos' => [
        'sigla' => 'MRK',
        'ordem' => 41,
        'nome' => 'Marcos',
        'abreviacao' => 'Mc',
        'arquivo' => 'marcos.json',
    ],
    'lucas' => [
        'sigla' => 'LUK',
        'ordem' => 42,
        'nome' => 'Lucas',
        'abreviacao' => 'Lc',
        'arquivo' => 'lucas.json',
    ],
    'joao' => [
        'sigla' => 'JHN',
        'ordem' => 43,
        'nome' => 'João',
        'abreviacao' => 'Jo',
        'arquivo' => 'joao.json',
    ],
    'atos' => [
        'sigla' => 'ACT',
        'ordem' => 44,
        'nome' => 'Atos',
        'abreviacao' => 'At',
        'arquivo' => 'atos.json',
    ],
    'romanos' => [
        'sigla' => 'ROM',
        'ordem' => 45,
        'nome' => 'Romanos',
        'abreviacao' => 'Rm',
        'arquivo' => 'romanos.json',
    ],
    '1-corintios' => [
        'sigla' => '1CO',
        'ordem' => 46,
        'nome' => '1 Coríntios',
        'abreviacao' => '1Co',
        'arquivo' => '1-corintios.json',
    ],
    '2-corintios' => [
        'sigla' => '2CO',
        'ordem' => 47,
        'nome' => '2 Coríntios',
        'abreviacao' => '2Co',
        'arquivo' => '2-corintios.json',
    ],
    'galatas' => [
        'sigla' => 'GAL',
        'ordem' => 48,
        'nome' => 'Gálatas',
        'abreviacao' => 'Gl',
        'arquivo' => 'galatas.json',
    ],
    'efesios' => [
        'sigla' => 'EPH',
        'ordem' => 49,
        'nome' => 'Efésios',
        'abreviacao' => 'Ef',
        'arquivo' => 'efesios.json',
    ],
    'filipenses' => [
        'sigla' => 'PHP',
        'ordem' => 50,
        'nome' => 'Filipenses',
        'abreviacao' => 'Fp',
        'arquivo' => 'filipenses.json',
    ],
    'colossenses' => [
        'sigla' => 'COL',
        'ordem' => 51,
        'nome' => 'Colossenses',
        'abreviacao' => 'Cl',
        'arquivo' => 'colossenses.json',
    ],
    '1-tessalonicenses' => [
        'sigla' => '1TH',
        'ordem' => 52,
        'nome' => '1 Tessalonicenses',
        'abreviacao' => '1Ts',
        'arquivo' => '1-tessalonicenses.json',
    ],
    '2-tessalonicenses' => [
        'sigla' => '2TH',
        'ordem' => 53,
        'nome' => '2 Tessalonicenses',
        'abreviacao' => '2Ts',
        'arquivo' => '2-tessalonicenses.json',
    ],
    '1-timoteo' => [
        'sigla' => '1TI',
        'ordem' => 54,
        'nome' => '1 Timóteo',
        'abreviacao' => '1Tm',
        'arquivo' => '1-timoteo.json',
    ],
    '2-timoteo' => [
        'sigla' => '2TI',
        'ordem' => 55,
        'nome' => '2 Timóteo',
        'abreviacao' => '2Tm',
        'arquivo' => '2-timoteo.json',
    ],
    'tito' => [
        'sigla' => 'TIT',
        'ordem' => 56,
        'nome' => 'Tito',
        'abreviacao' => 'Tt',
        'arquivo' => 'tito.json',
    ],
    'filemom' => [
        'sigla' => 'PHM',
        'ordem' => 57,
        'nome' => 'Filemom',
        'abreviacao' => 'Fm',
        'arquivo' => 'filemom.json',
    ],
    'hebreus' => [
        'sigla' => 'HEB',
        'ordem' => 58,
        'nome' => 'Hebreus',
        'abreviacao' => 'Hb',
        'arquivo' => 'hebreus.json',
    ],
    'tiago' => [
        'sigla' => 'JAS',
        'ordem' => 59,
        'nome' => 'Tiago',
        'abreviacao' => 'Tg',
        'arquivo' => 'tiago.json',
    ],
    '1-pedro' => [
        'sigla' => '1PE',
        'ordem' => 60,
        'nome' => '1 Pedro',
        'abreviacao' => '1Pe',
        'arquivo' => '1-pedro.json',
    ],
    '2-pedro' => [
        'sigla' => '2PE',
        'ordem' => 61,
        'nome' => '2 Pedro',
        'abreviacao' => '2Pe',
        'arquivo' => '2-pedro.json',
    ],
    '1-joao' => [
        'sigla' => '1JN',
        'ordem' => 62,
        'nome' => '1 João',
        'abreviacao' => '1Jo',
        'arquivo' => '1-joao.json',
    ],
    '2-joao' => [
        'sigla' => '2JN',
        'ordem' => 63,
        'nome' => '2 João',
        'abreviacao' => '2Jo',
        'arquivo' => '2-joao.json',
    ],
    '3-joao' => [
        'sigla' => '3JN',
        'ordem' => 64,
        'nome' => '3 João',
        'abreviacao' => '3Jo',
        'arquivo' => '3-joao.json',
    ],
    'judas' => [
        'sigla' => 'JUD',
        'ordem' => 65,
        'nome' => 'Judas',
        'abreviacao' => 'Jd',
        'arquivo' => 'judas.json',
    ],
    'apocalipse' => [
        'sigla' => 'REV',
        'ordem' => 66,
        'nome' => 'Apocalipse',
        'abreviacao' => 'Ap',
        'arquivo' => 'apocalipse.json',
    ],
];
