<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Livros do Antigo Testamento
|--------------------------------------------------------------------------
|
| "siglas" contém aliases possíveis encontrados em bases bíblicas.
| O gerador compara esses aliases com o início da referência e também
| tenta reconhecer o nome do arquivo TSV.
|
*/

return [
    'genesis' => [
        'ordem' => 1,
        'nome' => 'Gênesis',
        'abreviacao' => 'Gn',
        'arquivo' => 'genesis.json',
        'siglas' => ['GEN', 'Gen', 'Genesis'],
    ],
    'exodo' => [
        'ordem' => 2,
        'nome' => 'Êxodo',
        'abreviacao' => 'Êx',
        'arquivo' => 'exodo.json',
        'siglas' => ['EXO', 'Exod', 'Exodus'],
    ],
    'levitico' => [
        'ordem' => 3,
        'nome' => 'Levítico',
        'abreviacao' => 'Lv',
        'arquivo' => 'levitico.json',
        'siglas' => ['LEV', 'Lev', 'Leviticus'],
    ],
    'numeros' => [
        'ordem' => 4,
        'nome' => 'Números',
        'abreviacao' => 'Nm',
        'arquivo' => 'numeros.json',
        'siglas' => ['NUM', 'Num', 'Numbers'],
    ],
    'deuteronomio' => [
        'ordem' => 5,
        'nome' => 'Deuteronômio',
        'abreviacao' => 'Dt',
        'arquivo' => 'deuteronomio.json',
        'siglas' => ['DEU', 'Deut', 'Deuteronomy'],
    ],
    'josue' => [
        'ordem' => 6,
        'nome' => 'Josué',
        'abreviacao' => 'Js',
        'arquivo' => 'josue.json',
        'siglas' => ['JOS', 'Josh', 'Joshua'],
    ],
    'juizes' => [
        'ordem' => 7,
        'nome' => 'Juízes',
        'abreviacao' => 'Jz',
        'arquivo' => 'juizes.json',
        'siglas' => ['JDG', 'Judg', 'Judges'],
    ],
    'rute' => [
        'ordem' => 8,
        'nome' => 'Rute',
        'abreviacao' => 'Rt',
        'arquivo' => 'rute.json',
        'siglas' => ['RUT', 'Ruth'],
    ],
    '1-samuel' => [
        'ordem' => 9,
        'nome' => '1 Samuel',
        'abreviacao' => '1Sm',
        'arquivo' => '1-samuel.json',
        'siglas' => ['1SA', '1Sam', '1Samuel'],
    ],
    '2-samuel' => [
        'ordem' => 10,
        'nome' => '2 Samuel',
        'abreviacao' => '2Sm',
        'arquivo' => '2-samuel.json',
        'siglas' => ['2SA', '2Sam', '2Samuel'],
    ],
    '1-reis' => [
        'ordem' => 11,
        'nome' => '1 Reis',
        'abreviacao' => '1Rs',
        'arquivo' => '1-reis.json',
        'siglas' => ['1KI', '1Kgs', '1Kings'],
    ],
    '2-reis' => [
        'ordem' => 12,
        'nome' => '2 Reis',
        'abreviacao' => '2Rs',
        'arquivo' => '2-reis.json',
        'siglas' => ['2KI', '2Kgs', '2Kings'],
    ],
    '1-cronicas' => [
        'ordem' => 13,
        'nome' => '1 Crônicas',
        'abreviacao' => '1Cr',
        'arquivo' => '1-cronicas.json',
        'siglas' => ['1CH', '1Chr', '1Chronicles'],
    ],
    '2-cronicas' => [
        'ordem' => 14,
        'nome' => '2 Crônicas',
        'abreviacao' => '2Cr',
        'arquivo' => '2-cronicas.json',
        'siglas' => ['2CH', '2Chr', '2Chronicles'],
    ],
    'esdras' => [
        'ordem' => 15,
        'nome' => 'Esdras',
        'abreviacao' => 'Ed',
        'arquivo' => 'esdras.json',
        'siglas' => ['EZR', 'Ezra'],
    ],
    'neemias' => [
        'ordem' => 16,
        'nome' => 'Neemias',
        'abreviacao' => 'Ne',
        'arquivo' => 'neemias.json',
        'siglas' => ['NEH', 'Neh', 'Nehemiah'],
    ],
    'ester' => [
        'ordem' => 17,
        'nome' => 'Ester',
        'abreviacao' => 'Et',
        'arquivo' => 'ester.json',
        'siglas' => ['EST', 'Esth', 'Esther'],
    ],
    'jo' => [
        'ordem' => 18,
        'nome' => 'Jó',
        'abreviacao' => 'Jó',
        'arquivo' => 'jo.json',
        'siglas' => ['JOB', 'Job'],
    ],
    'salmos' => [
        'ordem' => 19,
        'nome' => 'Salmos',
        'abreviacao' => 'Sl',
        'arquivo' => 'salmos.json',
        'siglas' => ['PSA', 'Ps', 'Psa', 'Psalms'],
    ],
    'proverbios' => [
        'ordem' => 20,
        'nome' => 'Provérbios',
        'abreviacao' => 'Pv',
        'arquivo' => 'proverbios.json',
        'siglas' => ['PRO', 'Prov', 'Proverbs'],
    ],
    'eclesiastes' => [
        'ordem' => 21,
        'nome' => 'Eclesiastes',
        'abreviacao' => 'Ec',
        'arquivo' => 'eclesiastes.json',
        'siglas' => ['ECC', 'Eccl', 'Ecclesiastes'],
    ],
    'cantico-dos-canticos' => [
        'ordem' => 22,
        'nome' => 'Cântico dos Cânticos',
        'abreviacao' => 'Ct',
        'arquivo' => 'cantico-dos-canticos.json',
        'siglas' => ['SNG', 'Song', 'SongOfSongs', 'Canticles'],
    ],
    'isaias' => [
        'ordem' => 23,
        'nome' => 'Isaías',
        'abreviacao' => 'Is',
        'arquivo' => 'isaias.json',
        'siglas' => ['ISA', 'Isa', 'Isaiah'],
    ],
    'jeremias' => [
        'ordem' => 24,
        'nome' => 'Jeremias',
        'abreviacao' => 'Jr',
        'arquivo' => 'jeremias.json',
        'siglas' => ['JER', 'Jer', 'Jeremiah'],
    ],
    'lamentacoes' => [
        'ordem' => 25,
        'nome' => 'Lamentações',
        'abreviacao' => 'Lm',
        'arquivo' => 'lamentacoes.json',
        'siglas' => ['LAM', 'Lam', 'Lamentations'],
    ],
    'ezequiel' => [
        'ordem' => 26,
        'nome' => 'Ezequiel',
        'abreviacao' => 'Ez',
        'arquivo' => 'ezequiel.json',
        'siglas' => ['EZK', 'Ezek', 'Ezekiel'],
    ],
    'daniel' => [
        'ordem' => 27,
        'nome' => 'Daniel',
        'abreviacao' => 'Dn',
        'arquivo' => 'daniel.json',
        'siglas' => ['DAN', 'Dan', 'Daniel'],
    ],
    'oseias' => [
        'ordem' => 28,
        'nome' => 'Oseias',
        'abreviacao' => 'Os',
        'arquivo' => 'oseias.json',
        'siglas' => ['HOS', 'Hos', 'Hosea'],
    ],
    'joel' => [
        'ordem' => 29,
        'nome' => 'Joel',
        'abreviacao' => 'Jl',
        'arquivo' => 'joel.json',
        'siglas' => ['JOL', 'Joel'],
    ],
    'amos' => [
        'ordem' => 30,
        'nome' => 'Amós',
        'abreviacao' => 'Am',
        'arquivo' => 'amos.json',
        'siglas' => ['AMO', 'Amos'],
    ],
    'obadias' => [
        'ordem' => 31,
        'nome' => 'Obadias',
        'abreviacao' => 'Ob',
        'arquivo' => 'obadias.json',
        'siglas' => ['OBA', 'Obad', 'Obadiah'],
    ],
    'jonas' => [
        'ordem' => 32,
        'nome' => 'Jonas',
        'abreviacao' => 'Jn',
        'arquivo' => 'jonas.json',
        'siglas' => ['JON', 'Jonah'],
    ],
    'miqueias' => [
        'ordem' => 33,
        'nome' => 'Miqueias',
        'abreviacao' => 'Mq',
        'arquivo' => 'miqueias.json',
        'siglas' => ['MIC', 'Mic', 'Micah'],
    ],
    'naum' => [
        'ordem' => 34,
        'nome' => 'Naum',
        'abreviacao' => 'Na',
        'arquivo' => 'naum.json',
        'siglas' => ['NAM', 'Nah', 'Nahum'],
    ],
    'habacuque' => [
        'ordem' => 35,
        'nome' => 'Habacuque',
        'abreviacao' => 'Hc',
        'arquivo' => 'habacuque.json',
        'siglas' => ['HAB', 'Hab', 'Habakkuk'],
    ],
    'sofonias' => [
        'ordem' => 36,
        'nome' => 'Sofonias',
        'abreviacao' => 'Sf',
        'arquivo' => 'sofonias.json',
        'siglas' => ['ZEP', 'Zeph', 'Zephaniah'],
    ],
    'ageu' => [
        'ordem' => 37,
        'nome' => 'Ageu',
        'abreviacao' => 'Ag',
        'arquivo' => 'ageu.json',
        'siglas' => ['HAG', 'Hag', 'Haggai'],
    ],
    'zacarias' => [
        'ordem' => 38,
        'nome' => 'Zacarias',
        'abreviacao' => 'Zc',
        'arquivo' => 'zacarias.json',
        'siglas' => ['ZEC', 'Zech', 'Zechariah'],
    ],
    'malaquias' => [
        'ordem' => 39,
        'nome' => 'Malaquias',
        'abreviacao' => 'Ml',
        'arquivo' => 'malaquias.json',
        'siglas' => ['MAL', 'Mal', 'Malachi'],
    ],
];
